all:
  vars:
    ansible_user: deploy
  children:
    production:
      hosts:
        62.146.168.92:
    staging:
      hosts:
        194.163.167.168:
    internal:
      hosts:
        157.173.100.1:
    app_vms:
      children:
        production:
        staging:
