name: 'Docker Build and Push'
description: 'Build and push Docker image to registry'
inputs:
  context:
    description: 'Build context path'
    required: true
  image-name:
    description: 'Full image name'
    required: true
  tags:
    description: 'Newline-separated list of tags'
    required: true
  registry:
    description: 'Registry type: docker-hub or ghcr'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password/token'
    required: true
outputs:
  image-digest:
    description: 'Image SHA256 digest'
    value: ${{ steps.build.outputs.digest }}
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry == 'ghcr' && 'ghcr.io' || '' }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and Push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max