name: 'Health Check'
description: 'Check service health endpoint with retry logic'
inputs:
  url:
    description: 'Health check URL'
    required: true
  max-attempts:
    description: 'Maximum retry attempts'
    required: false
    default: '5'
  retry-delay:
    description: 'Delay between retries (seconds)'
    required: false
    default: '10'
runs:
  using: 'composite'
  steps:
    - name: Check endpoint health
      uses: jtalk/url-health-check-action@v4
      with:
        url: ${{ inputs.url }}
        max-attempts: ${{ inputs.max-attempts }}
        retry-delay: ${{ inputs.retry-delay }}s